# Generated by Django 2.0 on 2018-02-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blat',
            name='via',
        ),
        migrations.AddField(
            model_name='blat',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
